stages:
  - name: "Build"
    type: "npm"
    script: |
      npm install
      npm run build

  - name: "Unit Tests"
    type: "npm"
    script: |
      npm test

  - name: "Release"
    type: "cf-deploy"
    script: |
     cf login -a https://api.cf.us10-001.hana.ondemand.com -u "DARSHAN G" -p "Darshan@2002"
     cf push


notifications:
  - type: "email"
    recipients:
      - "darshanganesh23@gmail.com"
    on_failure: true
    on_success: true

build_retention:
  days: 30
